# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  -   repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.0.1
      hooks:
        -   id: trailing-whitespace
        -   id: end-of-file-fixer
        -   id: name-tests-test
#        -   id: check-added-large-files
  -   repo: https://github.com/psf/black
      rev: 21.12b0
      hooks:
        -   id: black
            name: Auto-Formatting Python Code
            exclude: cookie_recipes

  -   repo: https://gitlab.com/pycqa/flake8
      rev: 3.9.2
      hooks:
        -   id: flake8
            name: Check Python Code Style
            exclude: cookie_recipes

  -   repo: https://github.com/PyCQA/isort
      rev: 5.10.1
      hooks:
        -   id: isort
            name: Sort Python Imports

  -   repo: https://github.com/pre-commit/pygrep-hooks
      rev: v1.9.0
      hooks:
        -   id: python-no-eval
